### ISSUE TITLE
Support for xstyled/styled-components

### ISSUE THREAD

**Issue by rafalschmidt97** [styled-components/webstorm-styled-components#107]
* **IDE name and version:** 2022.2.3

* **Styled-components plugin version:**  222.4345.14

## Problem description:

I wish there will be a support for xstyled theme variables. Are you planing to add it maybe?
https://xstyled.dev/docs/migrate-from-styled-components/

```css
import styled from '@xstyled/styled-components'

const Button = styled.button`
  padding-top: 2;
  padding-bottom: 2;
  padding-right: 4;
  padding-left: 4;
  color: white;
  border-radius: md;
  font-weight: semibold;
  transition: default;
  background-color: emerald-500; <--- variables without ${} syntax

  &:hover {
    background-color: emerald-800;
  }

  &:focus {
    outline: none;
    box-shadow: emerald-ring;
  }
`
```
